### ISSUE TITLE
System Tray doesn't show on KDE

### ISSUE THREAD

**Issue by Charadon** [flathub/com.github.debauchee.barrier#11]
Not sure if it works on other desktop environments, but on KDE the system tray doesn't show. If you configure barrier to minimize to system tray, the program will effectively become uncontrolable.
Running:
OpenSUSE Leap 15.1
KDE Plasma 5.12.8

**Comment by bergmannf** [comment]
It also does not show on `Gnome` - I think it is how the application is started:

```sh
ps aux | grep barrierc # for the client
/app/bin/barrierc -f --no-tray --debug INFO --name my_machine --enable-crypto [1.1.1.1]:24800
```

It seems the client is explicitly run with `--no-tray`, which sounds to me that it forces to not display any systray.

**Comment by ahayzen** [comment]
The system tray is missing because the own and talk name are missing from the permissions. 

You can workaround this issue by using a system override `sudo flatpak override --talk-name=org.kde.StatusNotifierWatcher --own-name=org.kde.* com.github.debauchee.barrier` or user override `flatpak override --user --talk-name=org.kde.StatusNotifierWatcher --own-name=org.kde.* com.github.debauchee.barrier`

I have submitted a merge request to add these to the manifest.
